# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semodel', '0002_auto_20170122_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='intext',
            field=models.CharField(default='', max_length=500),
        ),
    ]
